# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "0 0,0,12,23 * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: lillian-who
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: lillian-who
        type: book
        format: csv
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './data/douban'



    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify  --baseURL https://dem1tasse.github.io
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true

